export const ADD_CURRENT_COORD_TO = 'ADD_CURRENT_COORD_TO'
export const ADD_CURRENT_COORD_FROM = 'ADD_CURRENT_COORD_FROM'
export const FIND_ROW_INDEX = 'FIND_ROW_INDEX'
export const SET_POLYLINE_ROUTE = 'SET_POLYLINE_ROUTE'